version: "3"
services:
  express:
    build: .
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    command: yarn dev
  postgres:
    image: postgres:13.6-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  prisma:
    build:
      context: ./nnecstasy-migration
      dockerfile: Dockerfile.prisma
    tty: true
